/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vehicle.online;

import io.quarkus.runtime.Quarkus;

public class VehicleApplication {
    public static void main(String[] args) {
        Quarkus.run(args);
    }
}
